import livePages from "./live-pages.json";
import legacyPages from "./legacy-pages.json";

export const primaryNav = [
  { label: "What we do", href: "/services" },
  { label: "Our work", href: "/case-studies" },
  { label: "Our process", href: "/our-process" },
  { label: "Our story", href: "/about" },
  { label: "Insights", href: "/blog" },
];

export const servicePages = [
  {
    route: "/mobile-and-web-app-development",
    code: "MC—APP",
    title: "Custom mobile, web & desktop app development",
    seoTitle: "Custom App Development Company — Mission Control",
    shortTitle: "Custom app development",
    description: "Mission Control is a UK app development company designing and building bespoke mobile, web and desktop applications across iOS, Android, macOS, Windows, Linux and the web.",
    image: "/assets/legacy/wp-content/uploads/2025/03/mobile-web-app-hero-img.png",
    statement: "Every platform. One product vision.",
    intro: [
      "Since 2013, we have designed and built digital products for organisations ranging from ambitious start-ups to the NHS, Mars, Oxford University Press and Dictionary.com.",
      "Some missions begin with a sketch. Others arrive with years of data, existing infrastructure and several audiences to satisfy. We bring product thinking, interface design and engineering together so the result works as one coherent service — not a collection of disconnected screens.",
    ],
    capabilities: [
      ["Mobile applications", "Native and cross-platform applications for iPhone, iPad, Android and specialist devices, including store preparation and release management."],
      ["Web platforms", "Customer-facing services, complex editorial products, account areas, dashboards and operational tools built for real-world traffic."],
      ["Desktop software", "Purpose-built experiences for macOS, Windows and Linux where browser software is not the right answer."],
      ["Systems & integrations", "Payments, identity, content systems, APIs, notifications, analytics and third-party services engineered as part of the product."],
    ],
    proof: [
      ["15+", "OUP language sites", "A five-year dictionary-platform programme connected to complex lexical data."],
      ["20,000", "Requests per minute", "Peak traffic managed across Oxford's dictionary properties."],
      ["iOS / Android / Web", "One product ecosystem", "Multi-channel delivery across healthcare, education, retail and accessibility."],
    ],
    deliverables: ["Product and technical discovery", "User experience and accessible interface design", "Native or cross-platform engineering", "Back-office systems and content management", "App-store and production launch", "Monitoring, support and continuous improvement"],
    projects: [
      ["Positive Signs", "ClickBSL", "A bespoke video platform connecting deaf users with British Sign Language interpreters."],
      ["Smart_R Education", "Mobile learning", "Gamified lessons, adaptive learning, social features and live progress across mobile and web."],
      ["Oxford University Press", "Dictionary platforms", "More than 15 high-traffic language properties supported over a five-year engagement."],
    ],
    related: [
      ["Mobile apps", "Mobile app development", "/mobile-app-development"],
      ["Apple platforms", "iOS app development", "/ios-app-development"],
      ["Android platforms", "Android app development", "/android-app-development"],
      ["Browser products", "Web app development", "/web-app-development"],
    ],
  },
  {
    route: "/mobile-app-development",
    code: "MC—MOB",
    title: "Mobile app development",
    seoTitle: "Mobile App Development Company UK — Mission Control",
    shortTitle: "Mobile app development",
    description: "Mission Control designs and builds secure, accessible mobile apps for iOS and Android, from product discovery and prototypes through launch and long-term support.",
    image: "/assets/legacy/wp-content/uploads/2025/03/mobile-web-app-dev-1.png",
    tier: "platform",
    statement: "Mobile products built for the world beyond the demo.",
    intro: [
      "Mission Control has delivered mobile applications since 2013 for healthcare, accessibility, learning, mobility, retail and consumer products. We work with established organisations and ambitious product teams that need more than a collection of screens.",
      "Every engagement connects the customer experience to the systems behind it: identity, payments, content, video, notifications, analytics, administration and the operational realities of app-store delivery.",
    ],
    capabilities: [
      ["Product & experience design", "Research, journeys, prototypes and accessible interface design shaped around the people who will use and operate the app."],
      ["iOS & Android engineering", "Native or cross-platform delivery selected around product needs, device capabilities, team constraints and expected lifespan."],
      ["Back-end & integrations", "Secure APIs, identity, payments, content, notifications, analytics and operational tools engineered as one service."],
      ["Launch & continuous delivery", "Testing, store submissions, production monitoring, release management and a practical roadmap after version one."],
    ],
    proof: [
      ["8+", "NHS condition apps", "Mobile self-management products supported by a central publishing platform for NHS teams."],
      ["iOS / Android / FireOS", "ClickBSL platforms", "A live video service connecting deaf users with British Sign Language interpreters."],
      ["6 months", "Smart_R delivery", "A gamified learning product launched across iOS, Android and web from one Flutter codebase."],
    ],
    deliverables: ["Mobile product discovery", "Accessible UX and interface design", "Native or cross-platform engineering", "API and back-office development", "App Store and Google Play launch", "Monitoring, support and product improvement"],
    projects: [
      ["Positive Signs", "ClickBSL", "Video calling, interpreter operations and accessibility features across iOS, Android and FireOS."],
      ["NHS", "Condition app programme", "More than eight apps helping people manage chronic and acute health conditions."],
      ["Smart_R Education", "Mobile learning", "Adaptive lessons, progress tracking, challenges and social features for GCSE learners."],
    ],
    related: [
      ["Apple platforms", "iOS app development", "/ios-app-development"],
      ["Android platforms", "Android app development", "/android-app-development"],
      ["All platforms", "Custom app development", "/mobile-and-web-app-development"],
    ],
  },
  {
    route: "/ios-app-development",
    code: "MC—IOS",
    title: "iOS app development",
    seoTitle: "iOS App Development Company UK — Mission Control",
    shortTitle: "iOS app development",
    description: "Mission Control designs, develops and supports bespoke iPhone and iPad applications, including product design, integrations, App Store launch and ongoing operation.",
    image: "/assets/legacy/wp-content/uploads/2025/03/mobile-web-app-dev-2.png",
    tier: "platform",
    statement: "Apple-platform experiences engineered around the product—not the store listing.",
    intro: [
      "We build iPhone and iPad applications that make considered use of the platform, from accessible everyday services to products involving video, notifications, secure accounts, payments and device hardware.",
      "The right implementation may be native iOS or part of a carefully designed cross-platform product. We make that decision from evidence, then take responsibility for the experience, engineering, release process and life after launch.",
    ],
    capabilities: [
      ["iPhone & iPad products", "Responsive experiences designed for Apple devices, interaction conventions, accessibility settings and real-world use."],
      ["Native device features", "Cameras, media, notifications, secure storage, location, NFC and other platform capabilities integrated where they add value."],
      ["Services & operations", "APIs, content systems, accounts, payments, analytics and administration tools delivered alongside the customer application."],
      ["App Store delivery", "Provisioning, testing, privacy declarations, review preparation, phased releases and ongoing version management."],
    ],
    proof: [
      ["8+", "NHS applications", "Condition-management apps delivered for iOS, Android and web with centrally managed clinical content."],
      ["NFC", "BikeAway access", "Customers book and unlock secure cycle storage from a connected mobile service."],
      ["On demand", "ClickBSL video", "An accessible mobile experience connecting users with interpreters and specialist support."],
    ],
    deliverables: ["iOS product and technical discovery", "iPhone and iPad experience design", "Native or cross-platform development", "Apple service and API integrations", "App Store submission and release", "Monitoring, maintenance and upgrades"],
    projects: [
      ["BikeAway", "NFC cycle-hub access", "Booking, payments and offline-capable unlocking brought together in one mobile service."],
      ["Positive Signs", "ClickBSL", "Video interpreting, document sharing and support designed around accessibility."],
      ["NHS", "Condition apps", "Trusted health guidance and self-management tools available on Apple devices."],
    ],
    related: [
      ["Mobile products", "Mobile app development", "/mobile-app-development"],
      ["Google platforms", "Android app development", "/android-app-development"],
      ["Planning", "App development cost guide", "/app-development-cost"],
    ],
  },
  {
    route: "/android-app-development",
    code: "MC—AND",
    title: "Android app development",
    seoTitle: "Android App Development Company UK — Mission Control",
    shortTitle: "Android app development",
    description: "Mission Control designs, builds and supports bespoke Android applications for phones, tablets and specialist devices, from discovery through Google Play release.",
    image: "/assets/legacy/wp-content/uploads/2025/03/mobile-web-app-dev-3.png",
    tier: "platform",
    statement: "Android products designed for varied devices and dependable operation.",
    intro: [
      "Android reaches far beyond a single handset. We design for the devices, environments, accessibility needs and operating conditions the product will actually encounter, including phones, tablets and specialist hardware.",
      "Mission Control handles the complete service around the app: product definition, experience design, engineering, integrations, testing, Google Play delivery, monitoring and support.",
    ],
    capabilities: [
      ["Android product design", "Journeys and interfaces shaped around platform conventions, responsive layouts, accessibility and varied device capability."],
      ["Native & cross-platform builds", "The implementation approach is selected around performance, hardware access, delivery constraints and future ownership."],
      ["Connected product systems", "Authentication, content, media, notifications, payments, analytics and administrative workflows integrated securely."],
      ["Google Play operations", "Testing tracks, store policy preparation, release management, crash monitoring and ongoing platform upgrades."],
    ],
    proof: [
      ["Android / iOS / Web", "Smart_R ecosystem", "One learning product with adaptive content, progress data and social features across platforms."],
      ["FireOS", "Beyond standard Android", "ClickBSL extended its accessible video service to Amazon devices as well as mobile platforms."],
      ["8+", "NHS condition apps", "A family of health products supported by shared publishing and operational tooling."],
    ],
    deliverables: ["Android discovery and requirements", "Accessible mobile interface design", "Native or cross-platform engineering", "Back-end and third-party integrations", "Google Play testing and release", "Monitoring, support and upgrades"],
    projects: [
      ["Smart_R Education", "Cross-platform learning", "A Flutter-based product delivering the same learning system across Android, iOS and web."],
      ["Positive Signs", "ClickBSL", "Accessible video calling and interpreter support on Android and FireOS."],
      ["NHS", "Condition apps", "Health information and self-management experiences delivered across mobile platforms."],
    ],
    related: [
      ["Mobile products", "Mobile app development", "/mobile-app-development"],
      ["Apple platforms", "iOS app development", "/ios-app-development"],
      ["Planning", "App development cost guide", "/app-development-cost"],
    ],
  },
  {
    route: "/web-app-development",
    code: "MC—WEB",
    title: "Web app development",
    seoTitle: "Web App Development Company UK — Mission Control",
    shortTitle: "Web app development",
    description: "Mission Control designs and engineers bespoke web applications, customer portals, operational platforms and high-traffic digital services for organisations across the UK.",
    image: "/assets/legacy/wp-content/uploads/2025/03/web-development-coding-digital.png",
    tier: "platform",
    statement: "Web products that do real work—not brochure sites in disguise.",
    intro: [
      "A web application may serve customers, editors, clinicians, operations teams or several audiences at once. We design the complete service so the public experience and the tools behind it remain coherent.",
      "Our web work spans high-traffic publishing, learning platforms, booking and payment systems, customer accounts, content management, reporting and complex data integrations.",
    ],
    capabilities: [
      ["Customer web applications", "Fast, responsive and accessible browser experiences designed around meaningful tasks rather than page templates."],
      ["Portals & operational tools", "Secure account areas, dashboards, publishing systems, administration and case-management workflows."],
      ["Data & integrations", "Identity, payments, content, lexical data, notifications, analytics and third-party APIs connected into dependable services."],
      ["Scale & operation", "Architecture, hosting, monitoring, security, performance and continuous delivery planned for the life of the product."],
    ],
    proof: [
      ["15+", "OUP language sites", "A five-year programme connecting high-traffic web properties to complex lexical data."],
      ["20,000", "Requests per minute", "Peak traffic supported across Oxford University Press dictionary properties."],
      ["2019", "Lexico launch", "Every page of the Dictionary.com and OUP platform was developed by Mission Control."],
    ],
    deliverables: ["Web product discovery", "Information architecture and accessible UX", "Front-end and back-end engineering", "CMS, accounts and operational tools", "Performance, security and deployment", "Hosting, monitoring and improvement"],
    projects: [
      ["Oxford University Press", "Dictionary platforms", "More than 15 language properties connected to a shared lexical-data ecosystem."],
      ["Dictionary.com × OUP", "Lexico", "A high-traffic dictionary product with bespoke editorial and content modules."],
      ["BikeAway", "Booking platform", "A web booking engine and administration system supporting connected cycle hubs."],
    ],
    related: [
      ["All platforms", "Custom app development", "/mobile-and-web-app-development"],
      ["Mobile products", "Mobile app development", "/mobile-app-development"],
      ["Existing platforms", "Modernisation and product rescue", "/support-modernisation-and-product-rescue"],
    ],
  },
  {
    route: "/ai-app-development",
    code: "MC—AIA",
    title: "AI app development",
    seoTitle: "AI App Development Company UK — Mission Control",
    shortTitle: "AI app development",
    description: "Mission Control designs and builds useful AI-powered mobile and web applications, combining responsible machine learning with production-grade product engineering.",
    image: "/assets/visuals/forpaws-feature.png",
    tier: "platform",
    statement: "AI belongs inside a useful, accountable product.",
    intro: [
      "An AI feature still needs a complete product around it: clear user value, dependable data, accessible interfaces, secure accounts, sensible fallbacks and a team responsible when the model is uncertain.",
      "Mission Control combines applied machine learning with mobile and web engineering. We can test the opportunity, prototype the critical behaviour and take the resulting application through evaluation, launch and monitored operation.",
    ],
    capabilities: [
      ["AI product discovery", "Use cases, data availability, success measures, risk and the role of human judgement defined before selecting a model."],
      ["Applied machine learning", "Recognition, classification, matching and generative capabilities integrated around a specific product need."],
      ["Mobile & web experience", "Interfaces that explain system behaviour, manage uncertainty and keep people in control of important outcomes."],
      ["Production evaluation", "Security, privacy, accuracy, failure modes, monitoring and operational review designed into the release."],
    ],
    proof: [
      ["96%+", "ForPaws accuracy", "A custom dog-recognition system developed for Mars Petcare and launched as a complete consumer product."],
      ["17", "Facial markers", "The neural network can use multiple features to identify an individual dog."],
      ["130+", "Recognised breeds", "The product handles varied breeds and difficult real-world photographs."],
    ],
    deliverables: ["AI opportunity assessment", "Data and evaluation planning", "Prototype and product experience", "Mobile or web application engineering", "Security, privacy and human oversight", "Launch monitoring and iterative improvement"],
    projects: [
      ["Mars Petcare", "ForPaws", "An AI-powered mobile product helping reunite owners with lost dogs."],
      ["Positive Signs", "Accessible assistance", "AI-assisted capabilities introduced within a human-led interpreting and support service."],
      ["Product teams", "Prototype to production", "Generated or experimental AI features audited and hardened for real customers."],
    ],
    related: [
      ["Agent workflows", "AI products and intelligent agents", "/ai-agent"],
      ["All platforms", "Custom app development", "/mobile-and-web-app-development"],
      ["Production readiness", "Modernisation and product rescue", "/support-modernisation-and-product-rescue"],
    ],
  },
  {
    route: "/app-development-cost",
    code: "MC—COST",
    title: "How much does app development cost?",
    seoTitle: "App Development Cost Guide — Mission Control",
    shortTitle: "App development cost guide",
    description: "A practical guide to the factors that shape mobile and web app development cost, including scope, platforms, integrations, compliance, launch and ongoing operation.",
    image: "/assets/legacy/wp-content/uploads/2025/03/mobile-web-app-dev-4.png",
    tier: "guide",
    pageType: "guide",
    schemaType: "Article",
    statement: "A credible estimate starts with scope, risk and operating reality.",
    intro: [
      "There is no responsible single price for an app before the product is understood. A focused prototype, an operational platform and a regulated multi-channel service have different teams, risks and lifespans even if each can be described as an app.",
      "The useful first step is to identify the product outcome, essential journeys, required platforms, data and integrations, assurance needs and what must happen after launch. From there, the work can be phased and estimated against explicit assumptions.",
    ],
    capabilities: [
      ["Product scope", "The number and complexity of user journeys, roles, content types and operational workflows usually matter more than a raw screen count."],
      ["Platforms & devices", "Native iOS, Android, cross-platform, web and desktop delivery carry different trade-offs for capability, testing and maintenance."],
      ["Data & integrations", "Identity, payments, legacy systems, hardware, content, analytics and third-party services can be central to the engineering effort."],
      ["Assurance & operation", "Accessibility, security, privacy, compliance, store review, monitoring, support and future releases belong in the product plan."],
    ],
    proof: [
      ["12 weeks", "ForPaws launch", "A tightly defined AI product moved from concept to live service at speed."],
      ["6 months", "Smart_R delivery", "A cross-platform learning product launched across mobile and web."],
      ["5+ years", "OUP programme", "A platform partnership expanded progressively as its audience, data and portfolio grew."],
    ],
    deliverables: ["Product outcome and audience definition", "Prioritised scope and assumptions", "Platform and architecture recommendation", "Integration and assurance assessment", "Phased delivery roadmap", "Evidence-based estimate and next step"],
    projects: [
      ["New product", "Discovery and prototype", "Reduce uncertainty before committing to production engineering."],
      ["Existing platform", "Audit and roadmap", "Protect valuable working software while identifying the highest-risk investments."],
      ["Multi-channel service", "Phased delivery", "Sequence customer apps, operational tools and integrations around usable releases."],
    ],
    related: [
      ["Mobile products", "Mobile app development", "/mobile-app-development"],
      ["Web products", "Web app development", "/web-app-development"],
      ["Early decisions", "Product strategy and prototyping", "/product-strategy-and-prototyping"],
    ],
  },
  {
    route: "/ai-agent",
    code: "MC—AIX",
    title: "AI products & intelligent agents",
    seoTitle: "AI Products & Intelligent Agents — Mission Control",
    shortTitle: "AI products that earn their place",
    description: "Mission Control designs responsible AI products, custom machine-learning systems and intelligent workflows grounded in a genuine user or business need.",
    image: "/assets/legacy/wp-content/uploads/2025/03/ai-agent-hero-img.png",
    statement: "Useful AI. No theatre.",
    intro: [
      "We have worked with artificial intelligence since long before every product needed an AI badge. Our approach starts with the outcome: what decision, task or experience can technology genuinely improve?",
      "That may mean a custom neural network, an intelligent workflow, assisted content processing or a carefully governed generative-AI feature. If a simpler solution is better, we will say so.",
    ],
    capabilities: [
      ["Custom machine learning", "Purpose-built recognition, classification and matching systems trained around the problem rather than a generic demo."],
      ["AI-assisted products", "Generative features integrated into complete products with appropriate review, fallbacks and human oversight."],
      ["Intelligent agents", "Workflow agents that connect approved data and business systems while preserving traceability and control."],
      ["Production governance", "Security, privacy, evaluation, monitoring and failure handling designed before an AI feature reaches customers."],
    ],
    proof: [
      ["96%+", "Matching accuracy", "Achieved by the ForPaws dog-recognition platform developed for Mars Petcare."],
      ["17", "Facial markers", "Used by the custom neural network to identify an individual dog."],
      ["130+", "Dog breeds", "Recognised by the system, including difficult low-light and off-centre photographs."],
    ],
    deliverables: ["AI opportunity and feasibility assessment", "Data and integration planning", "Prototype and evaluation framework", "Product interface and human oversight", "Secure production engineering", "Monitoring and iterative improvement"],
    projects: [
      ["Mars Petcare", "ForPaws AI", "A dog-recognition system whose success became a catalyst for a new product division."],
      ["Positive Signs", "ClickBSL", "AI-assisted translation, recording and support capabilities inside a human-led accessibility service."],
      ["Product teams", "AI build rescue", "Auditing generated code and turning promising prototypes into supportable products."],
    ],
    related: [
      ["Customer products", "AI app development", "/ai-app-development"],
      ["All platforms", "Custom app development", "/mobile-and-web-app-development"],
      ["Production readiness", "Modernisation and product rescue", "/support-modernisation-and-product-rescue"],
    ],
  },
  {
    route: "/product-strategy-and-prototyping",
    code: "MC—LAB",
    title: "App design, product strategy & prototyping",
    seoTitle: "App Design & Prototyping Company — Mission Control",
    shortTitle: "App design & prototyping",
    description: "Mission Control helps organisations research, design, prototype and plan new mobile and web applications before committing to a full production build.",
    image: "/assets/visuals/orbit-map.png",
    statement: "Find the right product before writing too much code.",
    intro: [
      "The earliest product decisions are often the most expensive to get wrong. We work with leadership teams, domain experts and users to turn an opportunity into a clear proposition, practical technical plan and testable experience.",
      "A prototype is not the finish line. It is a tool for answering questions, aligning stakeholders and reducing uncertainty before production engineering begins.",
    ],
    capabilities: [
      ["Product discovery", "Stakeholder workshops, user needs, success measures and commercial constraints translated into a shared mission brief."],
      ["Experience definition", "Journeys, information architecture and interface concepts that make the proposed service tangible."],
      ["Technical direction", "Architecture options, integrations, platform choices and delivery risks assessed before they become sunk cost."],
      ["Prototype programmes", "Focused demonstrators and MVPs designed to validate a proposition with users, partners or investors."],
    ],
    proof: [
      ["FT × Eurostar", "Loyalty prototype", "An end-to-end location-aware pass and rewards concept created with the FT innovation team."],
      ["Walmart", "Impulse commerce", "A Scan & Go concept subsequently adopted into the main application in multiple territories."],
      ["12 weeks", "Concept to live", "The initial ForPaws experience moved from product concept to launch at speed."],
    ],
    deliverables: ["Opportunity and audience definition", "Prioritised product requirements", "User journeys and service blueprint", "Interactive prototype or technical proof", "Architecture and platform recommendation", "Phased roadmap and investment plan"],
    projects: [
      ["Financial Times × Eurostar", "Passbook programme", "A loyalty and location-aware offers prototype connecting mobile wallets and member benefits."],
      ["Mediacom × Walmart", "Retail innovation", "Commerce prototypes that tested new behaviour before entering a global product ecosystem."],
      ["Mars Petcare", "ForPaws", "Product ideation, identity, experience design and engineering delivered as one programme."],
    ],
    related: [
      ["Planning", "App development cost guide", "/app-development-cost"],
      ["Mobile products", "Mobile app development", "/mobile-app-development"],
      ["All platforms", "Custom app development", "/mobile-and-web-app-development"],
    ],
  },
  {
    route: "/self-management-platforms",
    code: "MC—SELF",
    title: "Self-management platforms",
    shortTitle: "Digital services people can run themselves",
    description: "Mission Control builds self-service and self-management platforms for healthcare, learning, mobility, retail and specialist support services.",
    image: "/assets/live/clickbsl.png",
    statement: "Complex services made clear, useful and human.",
    intro: [
      "Some of our most valuable work helps people complete an important task without waiting in a queue, filling in paperwork or navigating a system designed around the organisation rather than the user.",
      "We combine customer applications with the operational tools behind them: content management, bookings, notifications, reporting, permissions and administration. Both sides of the service are designed together.",
    ],
    capabilities: [
      ["Customer applications", "Accessible mobile and web experiences for booking, learning, reporting, condition management and specialist support."],
      ["Operational consoles", "Dashboards and administration tools that help internal teams manage users, content, cases and service performance."],
      ["Content & communications", "Structured publishing, real-time alerts, personalised notifications and guidance managed by authorised teams."],
      ["Connected services", "Identity, payments, hardware access, law-enforcement reporting and specialist integrations brought into one workflow."],
    ],
    proof: [
      ["8+", "NHS condition apps", "Supporting people managing chronic and acute conditions across iOS, Android and web."],
      ["Hours → minutes", "Retail reporting", "RACK reduced a complex crime-reporting process to a guided mobile workflow."],
      ["NFC", "Keyless access", "BikeAway users can book and open secure cycle storage without connectivity."],
    ],
    deliverables: ["Service and user-journey design", "Accessible customer applications", "Administration and case-management tools", "Publishing and notification systems", "Reporting and operational analytics", "Deployment, training and support"],
    projects: [
      ["NHS", "Condition app programme", "More than eight apps and a central publishing system for NHS editors across the UK."],
      ["RACK", "Retail crime reporting", "Mobile incident capture connected to retailer management and law-enforcement workflows."],
      ["BikeAway", "Cycle-hub booking", "Booking, payment, administration and NFC access across a connected service."],
    ],
  },
  {
    route: "/support-modernisation-and-product-rescue",
    code: "MC—OPS",
    title: "Support, modernisation & product rescue",
    shortTitle: "Keep valuable products moving",
    description: "Mission Control audits, modernises and operates existing software, including inherited platforms and AI-built MVPs that need production hardening.",
    image: "/assets/live/blog-ai-app.webp",
    statement: "Bring us the roadmap—or bring us the mess.",
    intro: [
      "Not every worthwhile product begins with us. We take on inherited systems, ageing applications and AI-generated prototypes that have proved the idea but are not ready for customers, compliance reviews or sustained growth.",
      "We start by understanding what is valuable, what is fragile and what the organisation needs next. The result is a prioritised plan that protects working product value while removing operational risk.",
    ],
    capabilities: [
      ["Technical audit", "Architecture, dependencies, security, data flows, environments and maintainability assessed without judgement."],
      ["Production hardening", "Authentication, secrets, payments, GDPR, testing, monitoring and deployment brought to a dependable standard."],
      ["Modernisation", "Framework upgrades, platform migrations, interface renewal and targeted replacement of high-risk components."],
      ["Ongoing operation", "Release management, app-store submissions, monitoring, support and a practical improvement roadmap."],
    ],
    proof: [
      ["5+ years", "OUP engagement", "A long-running platform partnership covering product development, hosting and continuous refinement."],
      ["15+", "Connected properties", "One content and data ecosystem expanded across a global language portfolio."],
      ["5 signals", "Launch standard", "Security, privacy, stores, payments and maintainability checked before go-live."],
    ],
    deliverables: ["Codebase and infrastructure audit", "Prioritised risk and remediation plan", "Security and privacy hardening", "Upgrade and migration delivery", "Monitoring and release operations", "SLA-backed product support"],
    projects: [
      ["Oxford University Press", "Long-term platform operation", "Five years of development, integration, hosting and ongoing refinement."],
      ["Dictionary.com", "Lexico", "A high-traffic product operated with complex lexical-data integrations and editorial tooling."],
      ["AI-built products", "From prototype to production", "Focused rescue work that preserves the useful idea while replacing fragile foundations."],
    ],
  },
];

export const historyMilestones = [
  ["2013", "Mission Control is founded", "Eddie Vassallo establishes an independent product and software studio built around mobile experience, emerging technology and direct collaboration with clients."],
  ["2015", "Dictionary platforms begin to scale", "An initial Oxford University Press engagement grows from two language microsites into a much larger publishing and lexical-data programme."],
  ["2016", "Digital health at national scale", "The NHS condition-app programme brings guidance and self-management tools to people living with chronic and acute conditions."],
  ["2019", "Lexico launches", "Mission Control develops every page of Dictionary.com and Oxford University Press's Lexico platform, supported by bespoke editorial technology."],
  ["2020s", "Products move into more industries", "Retail commerce, crime reporting, mobility, pet technology, education and accessibility missions extend the studio's experience across complex services."],
  ["Today", "Building—and rescuing—the next generation", "The crew continues to create ambitious products from zero while helping organisations turn promising AI-built prototypes into secure, maintainable software."],
];

export const principles = [
  ["01", "People before features", "We begin with the people using and operating a service. Accessibility, empathy and clarity are product foundations, not a final compliance pass."],
  ["02", "The right tool for the mission", "Native, cross-platform and web technologies all have trade-offs. We select around users, lifespan, internal capability and the future of the product."],
  ["03", "Open by preference", "Linux, open standards and open-source software encourage transparency, adaptability and greater client control."],
  ["04", "Ownership without lock-in", "Clients should be able to understand, maintain and evolve the software they have funded. Documentation and sensible architecture matter."],
  ["05", "Sustainable over disposable", "We value repairable hardware, maintainable code and technology choices that can serve a product for years rather than a launch cycle."],
  ["06", "AI with accountability", "AI can accelerate good teams, but important products still need human judgement, security, testing and someone accountable for the outcome."],
];

export const footerServiceLinks = servicePages.map(({ route, shortTitle }) => ({ href: route, label: shortTitle }));

export const clients = [
  { name: "NHS", src: "/assets/clients/nhs.png" },
  { name: "Mars", src: "/assets/clients/mars.png" },
  { name: "Oxford University Press", src: "/assets/clients/oxford.png" },
  { name: "Dictionary.com", src: "/assets/clients/dictionary.png" },
  { name: "Financial Times", src: "/assets/clients/financial-times.png" },
  { name: "Pearson", src: "/assets/clients/pearson.png" },
  { name: "Mediacom", src: "/assets/clients/mediacom.png" },
  { name: "Art Fund", src: "/assets/clients/art-fund.png" },
];

export const processPhases = [
  {
    number: "01",
    timing: "T-minus 4 weeks",
    title: "Intake",
    copy: "We accept the codebase as-is, without judgement. We obtain repository access, hosting credentials and available documentation, then inventory what was built, assumed and omitted.",
  },
  {
    number: "02",
    timing: "T-minus 3 weeks",
    title: "Audit",
    copy: "The go/no-go poll: security, GDPR and data protection, app-store readiness, payments and maintainability — prioritised into a clear fixed-price plan.",
  },
  {
    number: "03",
    timing: "T-minus 2 weeks",
    title: "Harden",
    copy: "We remediate every red item: secrets, authentication, data flows, payment resilience, tests, environments, monitoring and deployment pipelines.",
  },
  {
    number: "04",
    timing: "T-zero",
    title: "Launch & hold",
    copy: "We manage store submissions and go-live, then hold the console with SLA-backed support, severity classifications, monitoring and alerts.",
  },
];

export const caseStudies = [
  {
    mission: "01",
    status: "Active",
    client: "Positive Signs",
    title: "ClickBSL",
    image: "/assets/live/clickbsl.png",
    copy: "A bespoke video-calling platform connecting deaf users to British Sign Language interpreters on demand, with document sharing, landline call-out and desktop technical assistance.",
    stats: [["Platforms", "iOS / Android / FireOS"], ["Interpreter ops", "Booking + scheduling + admin"], ["Status", "Live — clickbsl.com"]],
  },
  {
    mission: "02",
    status: "Complete",
    client: "Smart_R Education",
    title: "Smart_R eLearning apps",
    image: "/assets/live/smartr.png",
    copy: "A gamified mobile learning platform for GCSE students combining micro-lessons, adaptive learning journeys, real-time progress tracking, leaderboards and friend challenges.",
    stats: [["Build time", "6 months"], ["Platforms", "iOS / Android / Web"], ["Codebase", "Single Flutter app"]],
  },
  {
    mission: "03",
    status: "Complete",
    client: "Mars Petcare",
    title: "ForPaws AI",
    image: "/assets/visuals/forpaws-feature.png",
    copy: "An AI-powered mobile app helping owners locate lost dogs using a custom neural network that reads up to 17 facial markers and recognises more than 130 breeds.",
    stats: [["Match accuracy", "96%+"], ["Timeline", "12 weeks"], ["Outcome", "New Mars division created"]],
  },
  {
    mission: "04",
    status: "Complete",
    client: "NHS",
    title: "Condition app programme",
    image: "/assets/clients/nhs.png",
    copy: "A suite of self-management apps for chronic and acute conditions including HIV, diabetes, neonatal care, obesity and pregnancy, powered by a bespoke publishing system.",
    stats: [["Condition apps", "8+"], ["Platforms", "iOS / Android / Web"], ["Editors", "NHS teams across the UK"]],
  },
  {
    mission: "05",
    status: "Complete",
    client: "RACK",
    title: "Retail Action Crime Kit",
    image: "/assets/live/rack.png",
    copy: "A mobile app transforming retail-crime reporting from hours of paperwork into minutes, integrating reports directly with law-enforcement systems and hotspot analytics.",
    stats: [["Report time", "Hours → minutes"], ["Police integration", "Direct"], ["Recognition", "Industry innovation award"]],
  },
  {
    mission: "06",
    status: "Complete",
    client: "BikeAway",
    title: "Bike-hub booking",
    image: "/assets/live/bikeaway.png",
    copy: "A self-management booking system for cycle lockers with NFC unlocking, supported by iOS and Android apps, a web booking engine and an administration interface.",
    stats: [["Unlock method", "NFC — no key or QR"], ["Connectivity", "None required"], ["Deployment", "UK rail + public venues"]],
  },
  {
    mission: "07",
    status: "Complete",
    client: "Oxford University Press",
    title: "Dictionary platforms",
    image: "/assets/clients/oxford.png",
    copy: "A five-year engagement scaling from two African-language dictionary microsites to more than 15 language properties connected to OUP's lexical-data system.",
    stats: [["Engagement", "5+ years"], ["Language sites", "15+"], ["Peak traffic", "20,000 requests/min"]],
  },
  {
    mission: "08",
    status: "Ongoing",
    client: "Mediacom",
    title: "Retail app programmes",
    image: "/assets/clients/mediacom.png",
    copy: "Retail-commerce prototypes and MVPs including Walmart Scan & Go, subsequently adopted into Walmart's main application across multiple territories.",
    stats: [["Flagship", "Walmart Scan & Go"], ["Outcome", "Adopted into main app"], ["Territories", "US + France + Poland"]],
  },
  {
    mission: "09",
    status: "Complete",
    client: "Dictionary.com × OUP",
    title: "Lexico",
    image: "/assets/clients/dictionary.png",
    copy: "A major dictionary platform launched in 2019 with every page developed in-house, lexical-data integrations, Trending Words and Word of the Day modules.",
    stats: [["Launched", "June 2019"], ["Stack", "Rails + Remarkable CMS"], ["Operations", "Hosted and managed by MC"]],
  },
];

export const blogPosts = [
  {
    path: "/blog/why-cant-ai-just-build-this-app-for-us",
    code: "TX-04",
    category: "AI",
    date: "13 Feb 2026",
    title: "Why can't AI just build this app for us?",
    excerpt: "AI is a remarkable tool — one we use — but production software still depends on decisions, accountability and engineering discipline that prompts do not supply.",
    image: "/assets/live/blog-ai-app.webp",
  },
  {
    path: "/blog/picking-the-right-tool-for-the-job",
    code: "TX-03",
    category: "Engineering",
    date: "28 Aug 2025",
    title: "Picking the right tool for the job",
    excerpt: "Native, React Native and Flutter can all be right or wrong. The useful question is which constraints actually matter for the product in front of us.",
    image: "/assets/live/blog-right-tool.png",
  },
  {
    path: "/blog/framework-fairphone-we-like-our-hardware-like-our-software",
    code: "TX-02",
    category: "Hardware",
    date: "18 Aug 2025",
    title: "Framework & Fairphone — we like our hardware like our software",
    excerpt: "Modular, repairable and ours: hardware that changes with our needs, matching the open software we develop and love.",
    image: "/assets/live/blog-framework.jpg",
  },
  {
    path: "/blog/2025-the-year-of-the-linux-omarchy-desktop",
    code: "TX-01",
    category: "Linux",
    date: "16 Aug 2025",
    title: "2025: The year of the Linux (Omarchy) desktop",
    excerpt: "After years of distro-hopping, the console has settled. This might finally be the year of the Linux desktop.",
    image: "/assets/live/blog-omarchy.png",
  },
];

export const currentPageContent = livePages;
export const legacyPageMap = new Map(legacyPages.map((page) => [page.route.replace(/\/$/, "") || "/", page]));

export const allIndexableRoutes = [
  "/",
  "/services",
  ...servicePages.map((service) => service.route),
  "/our-process",
  "/case-studies",
  "/about",
  "/our-history",
  "/open-source-and-sustainable-development",
  "/contact",
  "/blog",
  ...blogPosts.map((post) => post.path),
  ...legacyPages.map((page) => page.route),
].filter((route, index, routes) => routes.indexOf(route) === index);
